# Generated by Django 3.1.8 on 2021-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=300, verbose_name='Recipient')),
                ('title', models.CharField(max_length=2000, verbose_name='mail title')),
                ('content', models.TextField(verbose_name='content of email')),
                ('send_result', models.BooleanField(default=False, verbose_name='result')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
            options={
                'verbose_name': 'Mail Send log',
                'verbose_name_plural': 'Mail Send log',
                'ordering': ['-created_time'],
            },
        ),
    ]
