# Generated by Django 3.1.8 on 2021-04-11 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='text')),
                ('created_time', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Create time')),
                ('last_mod_time', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Change the time')),
                ('is_enable', models.BooleanField(
                    default=True, verbose_name='Whether it is displayed')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent_comment', models.ForeignKey(blank=True, null=True,
                                                     on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='Superior comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
    ]
