# Generated by Django 3.1.8 on 2021-04-21 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['sequence'], 'verbose_name': 'links', 'verbose_name_plural': 'links'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_order',
            field=models.IntegerField(default=0, verbose_name='Sort by, the larger the number the higher the ranking'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default='o', max_length=1, verbose_name='Comment status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=1, verbose_name='Article Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('a', 'Article'), ('p', 'Page')], default='a', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Pageviews'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='article_sub_length',
            field=models.IntegerField(default=300, verbose_name='Article Summary Length'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='gongan_beiancode',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Public Security Record Number'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='open_site_comment',
            field=models.BooleanField(default=True, verbose_name='Whether to turn on the site comments'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='show_gongan_code',
            field=models.BooleanField(default=False, verbose_name='Whether to display the public security record number'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='show_google_adsense',
            field=models.BooleanField(default=False, verbose_name='Whether to show Google ads'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='sidebar_article_count',
            field=models.IntegerField(default=10, verbose_name='Number of sidebar articles'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='sidebar_comment_count',
            field=models.IntegerField(default=5, verbose_name='Number of sidebar comments'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='site_seo_description',
            field=models.TextField(default='', max_length=1000, verbose_name='Website SEO description'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='sitename',
            field=models.CharField(default='', max_length=200, verbose_name='Website name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='links',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Whether to display'),
        ),
        migrations.AlterField(
            model_name='links',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification time'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(verbose_name='Link Address'),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Link Name'),
        ),
        migrations.AlterField(
            model_name='links',
            name='show_type',
            field=models.CharField(choices=[('i', 'Homepage'), ('l', 'List'), ('p', 'Article page'), ('a', 'Full Site'), ('s', 'Friendship link page')], default='i', max_length=1, verbose_name='Display type'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Enabled or not'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification time'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='tag name'),
        ),
    ]
