# Generated by Django 3.1.8 on 2021-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210422_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettings',
            name='beiancode',
        ),
        migrations.RemoveField(
            model_name='blogsettings',
            name='gongan_beiancode',
        ),
        migrations.RemoveField(
            model_name='blogsettings',
            name='show_gongan_code',
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='analyticscode',
            field=models.TextField(default='', max_length=1000, verbose_name='analytics code '),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='google_adsense_codes',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Google adsense code'),
        ),
    ]
