# Generated by Django 3.1.8 on 2021-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210504_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='analyticscode',
            field=models.TextField(default='', verbose_name='Website analytics code '),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='google_adsense_codes',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='google adsense codes'),
        ),
    ]
