# Generated by Django 3.1.8 on 2021-04-21 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthuser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time'),
        ),
    ]
