# Generated by Django 3.1.8 on 2021-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20210422_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconfig',
            name='callback_url',
            field=models.CharField(default='http://www.medgloss.com', max_length=200, verbose_name='Callback address'),
        ),
    ]
