# Generated by Django 3.1.8 on 2021-05-07 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20210505_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'ordering': ['-created_time'], 'verbose_name': 'OAuth User', 'verbose_name_plural': 'OAuth User'},
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='weather enabled or not'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='type',
            field=models.CharField(choices=[('weibo', 'Weibo'), ('google', 'Google'), ('github', 'GitHub'), ('facebook', 'FaceBook'), ('qq', 'QQ')], default='a', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time '),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification time'),
        ),
    ]
